### ISSUE TITLE
Updates to the fb Graph API

### ISSUE THREAD

**Issue by DhiMalo** [criso/fbgraph#100]
Facebook's Graph API now (version 2.6) includes an ids parameter allowing multiple calls at once.  Recommend update npm docs (ReadMe) to include sample implementation code :-)* 

*Will do so myself if anyone else finds this helpful.

**Comment by criso** [comment]
👍 - if you can update the docs and send a pr woot! please do :)

**Comment by DhiMalo** [comment]
I've got a few other things on my plate at the moment but will plan to get to this soon! 👍 :)

**Comment by criso** [comment]
Updated to 2.4
