### ISSUE TITLE
Update default Graph API version 

### ISSUE THREAD

**Issue by ex1st** [criso/fbgraph#104]
I received a notice from Facebook:
> Graph API v2.0 will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences

I know about setVersion method, but may be default version should update to at least 2.1? Thanks.

**Comment by farnaz7** [comment]
*

**Comment by mskec** [comment]
@criso Are there plans to update default Graph API version?

**Comment by dibeesh** [comment]
Hi Team, 
Could you please let me know there any plans to migrate to latest Graph api version? Thank you.

**Comment by criso** [comment]
Updated to 2.4 :)

**Comment by dibeesh** [comment]
Thank you..
