### ISSUE TITLE
Tough-cookie package vulnerability

### ISSUE THREAD

**Issue by freakyfriday** [criso/fbgraph#105]
There is a vulnerability in the tough-cookie package used by the current request package version 2.69.0

See https://nodesecurity.io/advisories/130

Please upgrade the request package to version 2.74.1 as this uses the tough-cookie package 2.3.0 which doesn't have the above mentioned vulnerability.

**Comment by SherlockStd** [comment]
Good !

**Comment by freakyfriday** [comment]
Thanks Pierre :-) and thank you for building such a cool library.

cheers

Francesco

**Comment by SherlockStd** [comment]
@freakyfriday I'm not the developer ^^

**Comment by criso** [comment]
It seems that 2.74.1 isn't on npm yet. I've changed to 2.74.x so, we should be getting the update when possible. 
Great catch! Thanks!
