### ISSUE TITLE
v2.4 Update - issue with /posts  

### ISSUE THREAD

**Issue by nicolas-pickelny** [criso/fbgraph#106]
Hi, I was using the fbgraph v2.0 for getting the posts of a page, but now, with the v2.4 update, the response is retrieving fewer fields ( just postId, message and date). 
This module used to bring more fields for each post like
id, from: [Object],message, picture, name, type, etc

Is this version of the module going to keep the compatibility with the previous version or is just going to stay this way?

**Comment by criso** [comment]
That would be an update on the fb side of things. 
You could always set the api version that you want to a lower/previous version that was returning what you expected

https://github.com/criso/fbgraph#setting-the-version-of-the-graph-api
