### ISSUE TITLE
npm deprecation notice - node-uuid (via request: need update)

### ISSUE THREAD

**Issue by YasharF** [criso/fbgraph#115]
npm install warning:
npm WARN deprecated node-uuid@1.4.7: use uuid module instead npm WARN

This is because of the following dependency:
fbgraph@1.3.0  -> request@2.74.0 -> node-uuid@1.4.7

Updating the dependencies to the the latest version of request will fix this:

**Comment by YasharF** [comment]
PL to fix this issue:  https://github.com/criso/fbgraph/pull/116

**Comment by criso** [comment]
Pr merged - thanks!
