### ISSUE TITLE
Redirect user to Messenger Bot after authentification

### ISSUE THREAD

**Issue by TheDApact** [criso/fbgraph#117]
Hi, I am trying to login the user, then redirect him to my bot in Messenger? 
How would you do that following the Express example ?

**Comment by CQBinh** [comment]
Take a look at this snip code: 
```
var authUrl = graph.getOauthUrl({
        "client_id":     conf.client_id
      , "redirect_uri":  conf.redirect_uri
    });
```

`redirect_uri` is the URI that Facebook will `redirect` the user after he loged-in and authrorizes your app. So, let pass your `webhook callback uri` in that field.
