### ISSUE TITLE
FB Graph v2.3 will die on July 10, 2017

### ISSUE THREAD

**Issue by tsheaff** [criso/fbgraph#127]
I received this email from Facebook:

=============

v2.3 Upgrade Reminder

Your App is currently accessing Graph API v2.3 which will reach the end of its 2-year lifetime on 10 July, 2017. We estimate 5 endpoints that your app calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.4 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.

Visit our changelog to see the full list of changes in all Graph API versions.

You can view this and other Developer Notifications related to your app, in the App Dashboard.

=============

Here is the link to the upgrade tool: https://developers.facebook.com/tools/api_versioning

**Comment by tsheaff** [comment]
@criso best way to proceed with this package?

**Comment by gorjuspixels** [comment]
@tsheaff you should be able to set the version you want:

```
const fbGraph = require('fbgraph')
const facebookAPIVersion = '2.10'
fbGraph.setVersion(facebookAPIVersion)
```
