### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by guyisra** [criso/fbgraph#135]
Is this package still maintained? Does it need more maintainers to help out?

**Comment by amenadiel** [comment]
ping @criso 
I use this library thoroughly, and I'll be happy to contribute.

**Comment by wilforlan** [comment]
@amenadiel some of the apis are depreciated

**Comment by BrandonCookeDev** [comment]
I don't think it is. There's a PR (#130) out there that fixes the deprecated API issue but it's been ignored for months.

**Comment by criso** [comment]
Yeah - haven't had time to do any work on this. 
I've merged some of the less impactful PRs.
I'll rev up a version on npm and do have plans of updating this - but honestly forking the code and iterating on it will be quicker

**Comment by guyisra** [comment]
@amendiel do you still have time to work on this? Perhaps @criso can make you a maintainer?

**Comment by amenadiel** [comment]
I use this library on a daily basis and I've been struggling with the (exagerated) API changes after Cambridge Analytica so yeah, I can spend a couple at least an hour each day looking at PRs and my employer would consider it part of my duties.

**Comment by amenadiel** [comment]
BTW people, even if the default version still says 2.4, it's up to the user to pass a newer version when calling `setVersion` method. I'm using version 2.12 and all endpoints I use (pages and post insights, marketing insights, token information and extension, user info, user accounts, etc) do still work. 

For sure, some of them could be wrapped into methods that would reduce the verbosity of the request, but template literals will take you a long way if you use them right.

**Comment by criso** [comment]
Awesome! Added @amenadiel as collaborator 🤘

**Comment by amenadiel** [comment]
Whoa! I'll start digging into issues and PR tonight
