### ISSUE TITLE
Extend long-term token

### ISSUE THREAD

**Issue by Philmod** [criso/fbgraph#46]
Hey,

Is it possible to extend the long-term token?

When I use the `extendAccessToken` method, the `expires` response decreases.  Does that mean that even the new token won't work after some time?

Thanks,
Philmod

**Comment by SimonEast** [comment]
I've been searching everywhere for a way to get a permanent access token for server-side requests to the API. I don't want to have to manually renew it every so often. Did anyone discover a way to do that?

The closest thing I've found is this:
https://stackoverflow.com/a/58878246/195835
...however it requires a long, laborious, manual review process to get a business account with a system user that never expires.

If anyone has a better solution I'd love to hear it.
