### ISSUE TITLE
permission manage_notifications?

### ISSUE THREAD

**Issue by ga12ru12** [criso/fbgraph#57]
I want to get notification of fb like that:
graph.get("/me/notifications",  function(err, q) {
        res.send(q);
});

But when I run, I'm received a error:
{
  "error": {
    "message": "(#200) Requires extended permission: manage_notifications",
    "type": "OAuthException",
    "code": 200
  }
}
How can i set permission for my request?
Thanks

**Comment by tejalpandya** [comment]
which permission apply for give these type of error : Requires extended permission manage_notification,oauthexception
