### ISSUE TITLE
Support promises

### ISSUE THREAD

**Issue by ksaitor** [criso/fbgraph#74]
Would be awesome to have promises.
E.g. with https://github.com/petkaantonov/bluebird

```javascript
fbgraph
.get('/me', {
  access_token: access_token
})
.then(function (res) {
  console.log(res);
})
.catch(function (err) {
  console.error(err);
})
```

FTW!

**Comment by criso** [comment]
How about a section in the docs on how to add bluebird to it?
If it can be done with `promisifyAll`, adding it to the the lib seems unnecessary

**Comment by Khrall** [comment]
Guys, why not?
