### ISSUE TITLE
fbgraph.get('me') is showing https error with no explaination

### ISSUE THREAD

**Issue by mclark4386** [criso/fbgraph#75]
I have the following code:

```
var FB = require('fbgraph');
FB.setAccessToken(req.params['tokenSecret']);
FB.get('me', function(error,data){
            if(!data||error){
                console.log("FB error(create):"+(!error?"nil error":JSON.stringify(error)));
                next(error);
            }else{
                console.log("FB success");
            }
});
```

I have tested the tokenSecret in the Graph API explorer and it worked perfectly. However, the output I get from node is:

```
FB error(create):{"message":"Error processing https request","exception":{}}
```

I've googled, but it wasn't very helpful: 
https://www.google.com/?gws_rd=ssl#safe=off&q=fbgraph+%22Error+processing+https+request%22

I've also tried changing 'me' to '/me', 'v2.2/me', 'me/friends', etc. and all seem to have the same result. I'm sure it's something wrong that I've done, but sense there isn't any exception it's extremely hard to tell what.

Thanks!

**Comment by davodesign84** [comment]
Hi mclark4386, how did you fix the issue?
