### ISSUE TITLE
Deprecating API v1.0

### ISSUE THREAD

**Issue by hermanbosma** [criso/fbgraph#77]
I'm getting stern emails from Facebook warning me not to use API v1.0 anymore. Outside of a few rule changes, the new(er) versions seems to work much the same, so I did a quick search and replace, and it didn't break my app.

**Comment by criso** [comment]
v1 is available until April 30, 2015 - You can use `setVersion`
https://github.com/criso/fbgraph/pull/69

**Comment by criso** [comment]
This can be changed after April 30, 2015
https://developers.facebook.com/docs/apps/changelog
