### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by mrmayfield** [criso/fbgraph#79]
graph
  .setOptions(options)
  .get("zuck", function(err, res) {
    console.log(res); // { id: '4', name: 'Mark Zuckerberg'... }
  });

See: http://stackoverflow.com/questions/23615961/social-framework-returns-803-cannot-query-users-by-their-username-username

**Comment by criso** [comment]
Good catch!
Just need to update the readme example - not a bug with `fbgraph`
