### ISSUE TITLE
Taging users in posts is not supported

### ISSUE THREAD

**Issue by caranicas** [criso/fbgraph#80]
Your documentation shows an example of posting to a friends wall. But this hasn't been supported since 2013 

https://developers.facebook.com/blog/post/2012/10/10/growing-quality-apps-with-open-graph/

When I tried I got an error back

    message: '(#200) Feed story publishing to other users is disabled for this application'

The work accepted work around is mentioning a friend in a post on your own wall by adding @[user-id] to the message, however I could not get that to work either.

https://developers.facebook.com/docs/sharing/opengraph/using-actions#tags

 I attempted 

    wallPost = {message: "@[#######] I'm gonna come at you like a spider monkey, chip!"}

However this didn't result in a tag, just the user id being being published in the message as plain text

If you have any insight into how I could accomplish this tagging work around It would be greatly appreciated.

**Comment by criso** [comment]
If you can get it work via a curl request, it should work with `fbgraph` 
It seems that the `tags` portion has to be sent in *addition* to  `message` portion
something like:
```
wallpost = {
  tags: "rickyBobby",
  message: "@[rickyBobby] I'm gonna..."
}
```
