### ISSUE TITLE
Is static graph.setAccessToken(access_token) global?

### ISSUE THREAD

**Issue by georgemickael-b** [criso/fbgraph#81]
I read somewhere that setAcessToken() is global and sets the access token for all the connected users. 
'A' sets the token . 'B' sets the token. 'A' posts something but it goes to 'B's Wall.
I am not sure if this is right.Need clarification,Big time.

**Comment by criso** [comment]
https://github.com/criso/fbgraph/issues/19
https://github.com/criso/fbgraph/pull/34
https://github.com/criso/fbgraph#static-access-token-used-on-all-calls
https://github.com/criso/fbgraph#to-use-a-specific-access-token-for-a-particular-request
