### ISSUE TITLE
Auto paging all results

### ISSUE THREAD

**Issue by iamchathu** [criso/fbgraph#93]
Hi, I need to get all the results. How to get all paged json data

**Comment by criso** [comment]
stackoverflow

**Comment by iamchathu** [comment]
http://stackoverflow.com/questions/33069383/paginating-facebook-graph-api-using-nodejs-fbgraph

**Comment by criso** [comment]
These might help:
http://stackoverflow.com/questions/5023757/how-does-paging-in-facebook-javascript-api-works?rq=1
http://stackoverflow.com/questions/4125191/search-facebook-events-and-pagination-graph-api?rq=1

**Comment by iamchathu** [comment]
Is there any new way for this?
