### ISSUE TITLE
FB Access Token

### ISSUE THREAD

**Issue by joaopedrok** [criso/fbgraph#94]
I have a doubt. I'm creating and app in iOS that will have a facebook login. So, sometimes i'll need to cross information from facebook with my database, then ill need to send the access token that a got in iOS app to my node backend. 

if i call setCurrentToken function every time for all users it will work? or i can get some wrong information for a user that will do a request at the same time?

is there a way to control it with your library?

**Comment by joaopedrok** [comment]
Other doubt is it possible to create fetched requests?

**Comment by criso** [comment]
Follow this: https://github.com/criso/fbgraph#to-use-a-specific-access-token-for-a-particular-request
