### ISSUE TITLE
"Service Unavailable" string wrongly accepted as valid response

### ISSUE THREAD

**Issue by watson** [criso/fbgraph#95]
I've just experienced an issue where the [`json.data`](https://github.com/criso/fbgraph/blob/8585362314c200aa24f44c81639caece4354177f/lib/graph.js#L170) property was actually the string "Service Unavailable". Shouldn't this normally have been caught by the module and be returned as a proper error object instead?

**Comment by criso** [comment]
So it was a 200 with that response? I guess we could check for that string on the response

**Comment by watson** [comment]
@criso I guess it must have been a 2xx if that's what the module checks for - Unfortunately I don't have a the response so I can't be sure. But in that case it's pretty lousy of facebook to response 200 :(

I think checking for "Service Unavailable" is a bit dodgy though. Maybe there is no good way to do this?

**Comment by criso** [comment]
Sweet - wasn't checking for statusCode :(
I've updated all the things now 1.4.0
