### ISSUE TITLE
handle https for oauth dialog url

### ISSUE THREAD

**Issue by camwes** [criso/fbgraph#96]
My app uses https and I am getting a problematic 302 since the graph url is not [https](https://github.com/criso/fbgraph/blob/master/lib/graph.js#L36). Shouldn't it just default to https? If not we should make the protocol dynamic

**Comment by criso** [comment]
yeah - should just default to https

**Comment by thiagoross** [comment]
Im getting the same issue with the message 'Error processing https request'

**Comment by amenadiel** [comment]
Endpoints are http by default since commit 5f499be793a0e6cc013d727d2b776fbada30a149

https://github.com/criso/fbgraph/blob/5f499be793a0e6cc013d727d2b776fbada30a149/lib/graph.js#L34-L37
